<a href="https://colab.research.google.com/github/Nicotinamide/jupyter/blob/main/liner_reg_by_torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install d2l

In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

true_w = torch.tensor([2,-3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w,true_b,1000)  ### synthetic_data函数具体内容见从零实现  人工生成数据集

In [ ]:
### 调用框架中现有API来读取数据data.TensorDataset 和 data.DataLoader ...
def load_array(data_arrays,batch_size,is_train=True):
  dataset = data.TensorDataset(*data_arrays)                  ### 将传入的数据捆绑？并未合并，函数获得小批量！！
  return data.DataLoader(dataset,batch_size,shuffle=is_train)

batch_size = 10
data_iter = load_array((features, labels), batch_size)

next(iter(data_iter))                             ### next(iter())其中iter()生成迭代器，而next()获得下一个元素，两者组合使用


In [20]:
#### 测试学习段
'''
X = torch.arange(100).reshape((-1,2))
y = torch.rand(50)
data_iter = load_array((X,y),10,is_train=False)
##next(iter(data_iter))
for X,y in data_iter:
  print(X,y)
'''

### 得到data_iter可以通过for来分批次将所有数据取出！！！

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]) tensor([0.4435, 0.5359, 0.5223, 0.9893, 0.0159, 0.5559, 0.2110, 0.4170, 0.1267,
        0.1650])
tensor([[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]) tensor([0.9760, 0.6152, 0.5633, 0.0073, 0.3367, 0.0997, 0.2977, 0.8366, 0.1045,
        0.0024])
tensor([[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]]) tensor([0.5692, 0.8944, 0.6273, 0.9464, 0.9599, 0.0032, 0.4709, 0.2342, 0.3282,
        0.4412])
tensor([[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
    

In [13]:
### 使用框架的预定义好的层
from torch import nn
net = nn.Sequential(nn.Linear(2,1))                    ### Sequential()容器list of layers将层按顺序一个个放在一起  nn.Linear() 

In [14]:
net[0].weight.data.normal_(0,0.01)                ### 随机初始化w与b
net[0].bias.data.fill_(0)

tensor([0.])

In [15]:
### MSELoss 均方误差  L2
loss = nn.MSELoss()

In [16]:
### SGD实例
trainer = torch.optim.SGD(net.parameters(),lr=0.03)       ### 传入所有参数，并定义学习率

In [17]:
### 训练代码
num_epochs = 3
for epoch in range(num_epochs):
  for X,y in data_iter:
    l = loss(net(X),y)
    trainer.zero_grad()
    l.backward()
    trainer.step()
  l = loss(net(features),labels)
  print(f'epoch {epoch +1}, loss {l:f}')

epoch 1, loss 0.000187
epoch 2, loss 0.000098
epoch 3, loss 0.000099
